[package]
name = "hello-rust"
version = "1.0.0"
edition = "2021"
license-file = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }
